### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by cmer** [fboender/multi-git-status#12]
It'd be fantastic if this were added to Homebrew.

**Comment by fboender** [comment]
Hey Carl!

Thanks for the feature request. It's always nice if it's easier for users to install a tool. Unfortunately, as I don't use Homebrew myself, and I'm very busy with other projects (among other things), I don't have the time to figure out how it works and support it in the future. It's also not hard to install multi-git-status in its current form, I believe.

So I'm afraid I'm going to have to decline this feature request, but thank you for suggesting it!

**Comment by mikelorant** [comment]
Feel free to use this Formula if you want.

https://github.com/mikelorant/homebrew-custom/blob/master/Formula/multi-git-status.rb
