### ISSUE TITLE
Conf file to exclude git repositories by certain filters

### ISSUE THREAD

**Issue by GaurangTandon** [fboender/multi-git-status#14]
Hi, great tool! Is it possible to add support for a conf file which contains a list of patterns for repos that should not be checked for git status? 

Reason being, I have cloned several git repos over the past time that I wish to keep on my laptop, but I won't be updating them any time. So, I don't want to keep seeing `unpushed/unpulled changes` for them every time I run `mgitstatus`.

Of course, one way to do this would be to remove the `.git` folder from the individual git repos, but I have a lot of them, and doing this for each of them everytime I clone them can be time consuming.

Instead, I would appreciate if `mgitstatus` would check - on launch - for a conf file, which looks like:

```
pattern1
pattern2
...
```

and exclude git repos whose absolute path matches these patterns.

If you're happy to accept such a feature, would you mind me creating a PR for the same?

**Comment by fboender** [comment]
Hi Gaurang!

Good idea! I think the best approach is to use git's own configuration ability. See https://git-scm.com/docs/git-config for more info on that. Basically, git allows third-party tools to set configuration options in the `.git/config` file and use them.

I've gone ahead and implemented that in commit bcc984c. From the README.md:

    To ignore a repo, set the `mgitstatus.ignore` git configuration option for that repo to true. E.g.:
    
    $ cd stupidrepo
    $ git config --local mgitstatus.ignore true

Thanks for suggesting the feature!

**Comment by GaurangTandon** [comment]
Thanks for implementing it, I didn't know that!
