### ISSUE TITLE
"backing up" a git tree

### ISSUE THREAD

**Issue by bexelbie** [fboender/multi-git-status#20]
I started writing a patch and then abandoned it to add a feature that would provide the clone and repo commands required to duplicate a git directory tree.

Is this of interest?  It feels tangentially related at best but would be useful for me, at least.

I could even imagine a hybrid mode where the output is (theoretically) a list of directories with uncommitted work that should be backed up as files and a list of git commands that will recreate all other repos in their correct location with their correct remotes.

WDYT?

**Comment by fboender** [comment]
Hey Brian!

Sounds like it could use some of the code of multi-git-status, but I feel it's not related enough to mgitstatus's purpose to be an actual part of it. It's also not directly useful for me I think. Normally I wouldn't be against adding features that I might not use myself, but then they should follow the goal of the project itself.

I was thinking whether it might be useful to abstract some of mgitstatus' stuff away in a little shell library, but it's probably not worth the maintenance trouble.

So thanks for the consideration, but I'll probably decline adding this to mgitstatus.
