### ISSUE TITLE
syntax examples out of sync

### ISSUE THREAD

**Issue by abathur** [fboender/multi-git-status#25]
_Aside: Nice script. Glad you recently made a release. I'll probably submit a Nix package for it in the near future._

Entries 2 & 3 in the examples section (homepage & manpage) don't square with the supported syntax or documented synopsis:

    $ mgitstatus 3
    find: '3': No such file or directory

    $ mgitstatus -e --no-stashes 3 /opt/deploy
    /nix/store/m6l0dpi6xmgjs1mrsccgq3hv7c9bjx1l-mgitstatus-1.0/bin/mgitstatus: line 102: [: /opt/deploy: integer expression expected
    find: Expected a positive decimal integer argument to -maxdepth, but got '/opt/deploy'

FWIW (I realize it's not practical to change the syntax right after you hit 1.0, but just in case it's helpful to have syntax feedback) I think the example syntax with path as the final argument is a little less surprising than the supported syntax.

**Comment by fboender** [comment]
Thanks, I fixed the README and man page.

> FWIW (I realize it's not practical to change the syntax right after you hit 1.0, but just in case it's helpful to have syntax feedback) I think the example syntax with path as the final argument is a little less surprising than the supported syntax.

Yeah, I'm not too happy with the syntax either. I don't really like either options. I guess depth should have been an argument like `-d`. I could still do that in a backwards-compatible way by adding `-d`, and still supporting a depth after the path, but just don't mention it in the documentation. I'll give that some more thought and if I don't think of any objections, I'll probably do that.

Thanks for the feedback!
