### ISSUE TITLE
[Question]/suggestion: Auto add to your path? or dot file?

### ISSUE THREAD

**Issue by ashrodan** [fboender/multi-git-status#28]
Just reading through the docs maybe the installation steps could assist noobs (like myself).

Is there a recommended way to install mgitstatus globally?

I was able to do this with just an alias in my ~.bash_profile.
`alias mgitstatus='~/<path to parent folder>/multi-git-status/mgitstatus'`

But wondering if there was a better way or creating an install script?

p.s. Love the script btw. I did this using a bash command but this way more descriptive and feature-rich 😄

**Comment by SuperSandro2000** [comment]
I put it in ``$HOME/.local/bin/`` and Ubuntu default ``.profile`` has the following to add it to ``$PATH`` automatically.

````
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi
````

**Comment by fboender** [comment]
I've created an installer script that can install globally or locally. Check the README for instructions.

Thanks for the feedback!
