### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by bexelbie** [fboender/multi-git-status#33]
This act will trigger a bunch of distributions to update.  Without it, distributions need to switch to git hashes instead of versions.

**Comment by fboender** [comment]
Hey Brian.

Can do!

I've just released v2.0. It's a major release because of backwards incompatibility (for the `--depth` switch). See https://github.com/fboender/multi-git-status/releases/tag/2.0

If there's anything else you need, please let me know!
