### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by fritzdacat** [fboender/multi-git-status#37]
Great tool! An installation via Composer would be great

**Comment by SuperSandro2000** [comment]
This is not a php project. Why should this be installable with composer?

**Comment by fboender** [comment]
Hey fritzdacat!

A composer install would add significant overhead for me for this project. And I agree with SuperSandro2000. This is not a PHP project, so it feels kinda wrong to package a shell script with a packaging tool for PHP.

There is however some effort under way to package mgitstatus for Debian (and thus Ubuntu). See this bugreport for more info: https://github.com/fboender/multi-git-status/issues/38. That should make installing it a lot easier.
