### ISSUE TITLE
Got blocked out of server because queries happened too quickly

### ISSUE THREAD

**Issue by dmusican** [fboender/multi-git-status#47]
This is a fabulous tool, thanks for putting it together.

I have a lot of my git remotes on an ssh server at my workplace. When using the tool on a directory with about 30 repos, it made too many ssh connections too quickly, which triggered the security software on the server, and I got blocked from the server for about 10 minutes. That was fun to diagnose. :)

Is there any way to throttle the tool so that it hits the remote server more slowly?

**Comment by fboender** [comment]
You guys come up against the weirdest real world issues ;-)

I'm assuming this is with the `-f` option?

I've just pushed a change to the master branch that implements a `--throttle` option. It'll wait for SEC seconds between `git fetch` invocations (i.e. you've specified the `-f` flag).

Example usage:

```
 $ mgitstatus -f --throttle 2 -d 1
./sec-tools: ok 
./multi-git-status: ok 
./mdpreview: ok 
./ansible-cmdb: Needs push (master) Uncommitted changes Untracked files
```

**Comment by dmusican** [comment]
Awesome, thanks so much for the fix.
