### ISSUE TITLE
Fork changes undetected

### ISSUE THREAD

**Issue by DaniSpringer** [fboender/multi-git-status#54]
I created a fork from a repo on GitHub and pulled my version to my machine via Git.
Later, I updated my fork from the original repo via GitHub, and running "multi git status" on my machine said "no changes". However going into the folder of the forked repo, and running "git pull", did find those changes and pull them.

Would it be possible to detect such changes in the future?

Thanks!

**Comment by fboender** [comment]
Have you tried using the `-f` option? Multi-git-status doesn't contact the remote repo by default, so it only knows about changes there if you use `-f`. This does a non-destructive (I hope) `git fetch` on the repo before checking the status.

**Comment by DaniSpringer** [comment]
@fboender thanks! Any way to verify it is indeed non destructive?

**Comment by DaniSpringer** [comment]
@fboender Thank you!
