### ISSUE TITLE
Add a flag to list branches

### ISSUE THREAD

**Issue by jonmann20** [fboender/multi-git-status#57]
Hello, thanks for the wonderful tool.

Would be great if there were a way to list branches other than master/main (regardless of status).

e.g.

```sh
mgitstatus --branches

./foo: ok
./bar: my_stale_feature_branch_here
```

**Comment by fboender** [comment]
Hey Jon,

Not sure what you mean by this. Mgitstatus already shows branches other than master/main if the require any action. For example, a branch `stale` which has not been pushed to upstream:

```
./multi-git-status-test: Needs upstream (stale) 
```

I have just added a `-b` switch to show the currently checked out branch in the output:

```
./fboender/multi-git-status (master): Needs push (master) Uncommitted changes 
```

**Comment by jonmann20** [comment]
Awesome, ya I think I was looking for somthing like that so I could see which repos locally were not on `master`.  Thanks for the update and keep up the good work 💪
