### ISSUE TITLE
A "no" depth option

### ISSUE THREAD

**Issue by peter-kehl** [fboender/multi-git-status#58]
Thank you for `mgitstatus` Ferry.

Could you consider a "no depth" option? Beneficial when passing all repository names that the user wants to check.

Furthermore, there are use cases when the user may get noise even from `-d 1` and the user would like "no depth." My recent use case:
- a development environment-only workspace repo (not producing any code/software itself): [camigo-workspace](https://github.com/peter-kehl/camigo-workspace). It exists to speed up code navigation & make it easier to run (Rust) compile checks/tests for multiple related "neighbor" repos.
- that workspace repo has symlinks to the "neighbor" repos, like `camigo` -> `../camigo`.
- when I run `mgitstatus -e -d 1 camigo*`, it reports the same repositories twice (once under the current directory, and once as symlinked through my workspace repo).

Thank you in advance for considering.

UPDATE: I've realized that I could run `mgitstatus -e camigo-workspace`. But that works only in this instance (because all other repos that I'm interested in are symlinked from under `camigo-workspace/`). So that is not a general solution.

**Comment by fboender** [comment]
I've implemented a `--no-depth` option that doesn't recurse into subdirectories at all:

```
 $ ls -l testtest/multi-git-status
lrwxrwxrwx 1 fboender fboender 20 May  1 09:29 testtest/multi-git-status -> ../multi-git-status/

$ mgitstatus --no-depth testtest
testtest: Uncommitted changes Untracked files 

$ mgitstatus --no-depth testtest/multi-git-status
testtest/multi-git-status: ok 
```

I think this is what you want?

**Comment by peter-kehl** [comment]
Wow. Yes yes. Thank you Ferry.
